import Head from "next/head";
import {ThemeProvider} from "@mui/material/styles";
import {Provider} from "react-redux";
import store from "@/redux/store";
import theme from "@/components/mui/ThemeConfig";
import "@/styles/globals.css";


export default function App({ Component, pageProps }) {
    return(
        <Provider store={store}>
            <ThemeProvider theme={theme}>
                <Head>
                    <title>next-market</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                </Head>
                <main>
                    {
                        Component.getLayout ?
                            Component.getLayout(
                                <Component {...pageProps} />
                            )
                            :
                            <Component {...pageProps} />
                    }
                </main>
            </ThemeProvider>
        </Provider>
    )
}
